# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Вход.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enter(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(501, 460)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(205, 70, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mail_input = QtWidgets.QLineEdit(Form)
        self.mail_input.setGeometry(QtCore.QRect(140, 190, 271, 20))
        self.mail_input.setObjectName("mail_input")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 47, 13))
        self.label_3.setObjectName("label_3")
        self.password_input = QtWidgets.QLineEdit(Form)
        self.password_input.setGeometry(QtCore.QRect(140, 240, 271, 20))
        self.password_input.setObjectName("password_input")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(-4, -8, 521, 491))
        self.label_4.setStyleSheet("background-color: rgb(123, 141, 118);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.log_in = QtWidgets.QPushButton(Form)
        self.log_in.setGeometry(QtCore.QRect(200, 300, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.log_in.setFont(font)
        self.log_in.setObjectName("log_in")
        self.label_4.raise_()
        self.label.raise_()
        self.mail_input.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.password_input.raise_()
        self.log_in.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Вход"))
        self.label_2.setText(_translate("Form", "e-mail или телефон"))
        self.label_3.setText(_translate("Form", "Пароль"))
        self.log_in.setText(_translate("Form", "Войти"))
