# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'запуск_мессенджера.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(501, 463)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(35)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 160, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(370, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.login = QtWidgets.QPushButton(Form)
        self.login.setGeometry(QtCore.QRect(60, 340, 121, 23))
        self.login.setObjectName("login")
        self.registration = QtWidgets.QPushButton(Form)
        self.registration.setGeometry(QtCore.QRect(340, 340, 121, 23))
        self.registration.setObjectName("registration")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(-14, -8, 521, 491))
        self.label_4.setStyleSheet("background-color: rgb(123, 141, 118);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.login.raise_()
        self.registration.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Добро пожаловать в"))
        self.label_2.setText(_translate("Form", "R-Messenger"))
        self.label_3.setText(_translate("Form", "Beta"))
        self.login.setText(_translate("Form", "Войти"))
        self.registration.setText(_translate("Form", "Зарегистрироваться"))
